# Generated by Django 4.2.2 on 2023-06-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perevaladded",
            name="coords",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pereval.coords",
            ),
        ),
    ]
