# Generated by Django 4.2.2 on 2023-06-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0003_images_pereval_images_title_alter_images_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="perevaladded", name="raw_data",),
        migrations.AlterField(
            model_name="perevalimages",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pereval.images",
            ),
        ),
    ]
