# Generated by Django 4.2.2 on 2023-06-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0004_remove_perevaladded_raw_data_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="PerevalImages",),
    ]
