# Generated by Django 4.2.2 on 2023-06-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0005_delete_perevalimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="perevaladded",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pereval.users",
            ),
            preserve_default=False,
        ),
    ]
