# Generated by Django 4.2.2 on 2023-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pereval", "0007_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perevaladded",
            name="autumn",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="spring",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="summer",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="winter",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
